version: '3'

services:
  web:
    image: 0xt4req/csrf_lab_poridhi:latest
    container_name: csrf_lab_web
    ports:
      - "8999:80"
    depends_on:
      - db
    environment:
      - DOCKER_ENV=true
    networks:
      - csrf_network
    restart: always

  db:
    image: mysql:8.0
    container_name: csrf_lab_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: csrf_lab
      MYSQL_USER: csrf_user
      MYSQL_PASSWORD: csrf_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - csrf_network
    restart: always

networks:
  csrf_network:
    driver: bridge

volumes:
  db_data: